version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: housing_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: housing_db
    ports:
      - "5432:5432"
    volumes:
      # Esta es la instrucción que inyecta tu script
      - ./database/v1-initial-schema.sql:/docker-entrypoint-initdb.d/v1-initial-schema.sql
      # Esta línea garantiza que los datos no se borren al apagar el PC
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
